### ISSUE TITLE
The types of operands need to be reworked

### ISSUE THREAD

**Issue by bchurchill** [eschkufz/x64asm#114]
The types of operands work great for the assembler itself, but for any client of x64asm (including stoke) they're a big pain to work with.  From what I can tell, there's the "static" type, which doesn't mean much of anything.  We do dynamic casts to and from these types depending on what we want to typecheck.  At the same time, we also keep track of types in two different ways dynamically.  On one hand, we use the upper 61 bits of the val2_ field to get the type, and this is what I've been using the most recently.  On the other, we also use the type() method on instructions to get the correct type of an operand for a cast.

Typically I want to get an operand from an instruction (without knowing its type), and query things like its type or its width.  Right now, it's a guessing game to figure out what the type should be -- the static one?  the dynamic one?  the one stored in the instruction?  The type system and or dynamic checks should make sure there's one unique type per object.

**Comment by bchurchill** [comment]
Yeah.  All that makes sense.  I've been thinking about this a little
more.  The "dynamic" typing that I've implemented is actually free as
long as you don't use any of the "polymorphic" functions except when you
create the Operand object for the first time.  The "polymorphic"
functions just use the tagged type in their computation, and it might be
slower than built-in polymorphism -- although I'm not sure -- but I'm
okay with that.  The assembler/sandbox doesn't need to pay the cost
since it doesn't use these functions.  In the validator, I don't think
these costs are important enough to worry about

What I'm thinking about is this: we keep all the types roughly as they
are, but make a new rule that says that the static type always matches
the dynamic type.  As it is, this is true when Operands are constructed,
so long as they aren't casted around.  If we just write cast operators
to add all the conversions we want and update the types correctly, then
I feel like this would take care of most of the problem.  I think lots
of small local changes would be made to get details right, like loading
the correct argument types into instructions.

**Comment by eschkufz** [comment]
I think that sounds like a good plan. I could make a commitment to using
cast operators to make sure that the invariant holds.

**Comment by eschkufz** [comment]
I think we've come to an agreement on this and can make local edits towards this as we go in separate tickets. Probably no reason to keep this ticket open anymore.

Reopen if you disagree.
