### ISSUE TITLE
Invalid instruction variants allowed

### ISSUE THREAD

**Issue by eschkufz** [eschkufz/x64asm#12]
The x64asm type system is insufficient for preventing users from requesting instruction such as:

```crc32 %r12, %ah```

(This shouldn't be allowed due to %r12 requiring a rex prefix.)

This occurs for other instructions in similar situations, such as when a memory operand requires an rex prefix. Fixing this issue will require a major re-architecting. I'd prefer to stay away from this is possible.

Known opcodes with this issue --
- crc32
- movsx
- movzx

**Comment by stefanheule** [comment]
I will implement a dynamic check in Instruction::check() for this.  In the future, we might reevaluate the situation and decide to extend the type-system to catch this statically.
