### ISSUE TITLE
Expose implicit/explicit sets for Instruction

### ISSUE THREAD

**Issue by eschkufz** [eschkufz/x64asm#123]
These are private right now, but they're sort of useful to have.

**Comment by bchurchill** [comment]
I'm not following, which sets are these?

**Comment by eschkufz** [comment]
The must/maybe read/write/undef register sets.

Right now you have public methods: must/maybe_read/write/undef_set().
They're defined in terms of private methods that distinguish between
implicit an explicit sets. Implicit sets are those that are a function of
the opcode. Like how div writes rax/rdx. Explicit is the set that you get
by examining the instructions operands.

For using preserve_regs to prevent stoke from proposing push/pop for
example, I need to be able to ask what registers push/pop read/write/undef
without looking at the explicit operands.

On Tue, Jan 6, 2015 at 5:30 PM, Berkeley Churchill <notifications@github.com

**Comment by bchurchill** [comment]
Gotcha
