### ISSUE TITLE
Why is there no xsetbv?

### ISSUE THREAD

**Issue by stefanheule** [eschkufz/x64asm#125]
It seems that xsetbv is missing from opcode.enum (and other similar files), even though it is part of the spreadsheet.  Is this in purpose?  It's not important for me (or STOKE), but it seems odd that it's not there, when, e.g., xgetbv is there.

**Comment by eschkufz** [comment]
Check the permissions. It might be a ring<3 instruction. These are listed
as system in the spreadsheet.

**Comment by stefanheule** [comment]
Ah, indeed.  Thanks for the explanation.
