### ISSUE TITLE
RegSet::universe() doesn't contain %iopl

### ISSUE THREAD

**Issue by stefanheule** [eschkufz/x64asm#131]
But it should.

**Comment by bchurchill** [comment]
noooooooooo not another one

**Comment by stefanheule** [comment]
I'm actually wondering why the universe masks aren't just -1, but I decided that I don't want to investigate that, and only fix this for now.

**Comment by bchurchill** [comment]
Out of curiosity, why did you single out iopl?  My impression, I could
be wrong, is that this is only used for privileged operations.  I can't
imagine we support anything that uses it.

**Comment by stefanheule** [comment]
pushf(q) has the flag in it's read set.

**Comment by eschkufz** [comment]
I think the reason was that I was worried about comparisons against empty
(which don't work correctly anyway).

So for instance, if you set universe equal to 111111111 and you subtract
each of the rflags one by one you might get 110000100000100, which wouldn't
compare equal to empty 0000000000.

**Comment by stefanheule** [comment]
Shouldn't some kind of mask be used before any comparisons (that is, a 
mask that masks out the bits which aren't used)?

**Comment by eschkufz** [comment]
It could be, but would be slower and I didn't like the idea. I guess now
that we have a performance benchmarking script we could actually measure
the effect.

**Comment by stefanheule** [comment]
Ah, that makes sense.  But then surely we have assertions making sure the unused bits are always zero (or one, or whatever the convention is)? :P

**Comment by eschkufz** [comment]
Well that sounds like a lovely idea.

**Comment by bchurchill** [comment]
I would add a +1 for masking bits we don't want to use.  (cough: mxcsr) 
But I don't really care that much.

**Comment by stefanheule** [comment]
I'm not even just talking about those, as far as I know there's also bits in the representation of RegSets that just have no meaning whatsoever.

**Comment by bchurchill** [comment]
Yeah, understood.

**Comment by eschkufz** [comment]
Yeah. We don't use all of the 128 bits.

**Comment by bchurchill** [comment]
I imagine we'll put them to use when AVX-512 comes out :)
