### ISSUE TITLE
psllw

### ISSUE THREAD

**Issue by rknath** [eschkufz/x64asm#144]
Does psllw have wrong opcode ??

**Comment by bchurchill** [comment]
Yeah, there's indeed a bug in the spreadsheet where psllw with xmm, imm8 operands is listed twice, and one is wrong.  I have a fix for it but having a little trouble.  Hopefully I'll push the patch soon.

**Comment by rknath** [comment]
I tried to fix it but couldn't make it work . Was getting same result ..

On Friday, February 6, 2015, Berkeley Churchill <notifications@github.com>
wrote:

> Yeah, there's indeed a bug in the spreadsheet where psllw with xmm, imm8
> operands is listed twice, and one is wrong. I have a fix for it but having
> a little trouble. Hopefully I'll push the patch soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eschkufz/x64asm/issues/144#issuecomment-73353385>.
>


-- 
Rajib Nath
PhD Student, UCSD
http://cseweb.ucsd.edu/~rknath/

**Comment by eschkufz** [comment]
The bug looks like it's on line 1793:

0F 71 /6 ib PSLLW xmm1, imm8 MI RW, R V V MMX

The first operand should be mm1, not xmm1.

Fixing this is probably going to screw up some stuff in stoke since it's
going to mess with the ordering of the opcode table.

**Comment by bchurchill** [comment]
Also, this changes the number of opcodes because it thought they were the same before, and we know how many places that's hardcoded.  I thought this would be super fast to do, but seeing as it's not, I'm headed to bed.  If Eric doesn't take ownership of this by the time I get back to it I'll finish patching this up.  

@rknath if you want a quick-fix I think you can just delete the offending line 1793 entirely and *hopefully* everything will work.  Stoke doesn't do anything with mm registers anyway.

**Comment by eschkufz** [comment]
I'm not going to have a chance to look at this tonight.

It'll probably screw up the table for the latency cost function. I'm
skeptical about it just working.

**Comment by rknath** [comment]
Thanks a lot.
I was wondering if an automatic framework to validate the spreadsheet would
be useful.   everything is relying upon this. If the spreadsheet was
created manually then it's likely that there are more such bugs.


On Saturday, February 7, 2015, eric schkufza <notifications@github.com>
wrote:

> I'm not going to have a chance to look at this tonight.
>
> It'll probably screw up the table for the latency cost function. I'm
> skeptical about it just working.
>
> On Fri, Feb 6, 2015 at 11:30 PM, Berkeley Churchill <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Also, this changes the number of opcodes because it thought they were the
> > same before, and we know how many places that's hardcoded. I thought this
> > would be super fast to do, but seeing as it's not, I'm headed to bed. If
> > Eric doesn't take ownership of this by the time I get back to it I'll
> > finish patching this up.
> >
> > @rknath <https://github.com/rknath> if you want a quick-fix I think you
> > can just delete the offending line 1793 entirely and *hopefully*
> > everything will work. Stoke doesn't do anything with mm registers anyway.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/eschkufz/x64asm/issues/144#issuecomment-73353966>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eschkufz/x64asm/issues/144#issuecomment-73355143>.
>


-- 
Rajib Nath
PhD Student, UCSD
http://cseweb.ucsd.edu/~rknath/

**Comment by eschkufz** [comment]
It isn't immediately obvious to me how to validate the spreadsheet
automatically without also trying to maintain byte-for-byte agreement with
a known compiler.

 What's even worse is that that spreadsheet was originally generated by
copying text directly from the intel manual.That means that that bug most
likely appeared in the manual at one point as well.

**Comment by bchurchill** [comment]
I've been planning on doing testing, see #140.  That should help a ton, even if it's not formal validation.  I've found that we usually only tend to discover assembler bugs when we work on the validator, and we've been finding a bunch recently.

**Comment by rknath** [comment]
............. a quick-fix I think you can just delete the offending line 1793 entirely and hopefully everything will work............


doesn't seem like deleting line 1793 is working. 

any other quick fix suggestion ?

**Comment by rknath** [comment]
I guess .. the number of instructions is hard coded as 3803. It should be auto generated as well after parsing the x86.csv file ...

**Comment by stefanheule** [comment]
Yes, that number is hard-coded. We could automatically generate it, but we are not changing the number of instructions very often, so we are not currently planning on doing that.

**Comment by rknath** [comment]
I guess it is fixed for psllw now. 

It required two steps:

a) Editing x86.csv with the correct line

0F F1 /r        PSLLW mm, mm/m64        RM      RW, R                                           V       V       MMX     psllw           Shift words in mm left mm/m64 while shifting in 0s.
66 0F F1 /r     PSLLW xmm1, xmm2/m128   RM      RW, R                                           V       V       SSE2    psllw           Shift words in xmm1 left by xmm2/m128 while shifting in 0s.
0F 71 /6 ib     PSLLW mm, imm8  MI      RW, R                                           V       V       MMX     psllw           Shift words in mm left by imm8 while shifting in 0s.
66 0F 71 /6 ib  PSLLW xmm1, imm8        MI      RW, R                                           V       V       SSE2    psllw   YES     Shift words in xmm1 left by imm8 while shifting in 0s.

b) finding all hard coded number of opcodes in  /stoke/src src/tests or other places
   3803 - > 3804

Now all my psllw specific test case passes. 

@eschkufz you mentioned something about latency cost function may get affected. 
do I need to do more to preserve the correct functionality of stoke ?

**Comment by eschkufz** [comment]
The latency cost function is hard-coded in the table at
src/cost/tables/haswell which gets #include'd in src/cost/cost_function.

There's an entry in the table for each opcode, so if you've added a new
opcode, the table will have an off-by-one error in it now. The thing to do
is look up the new enum that's been generated in x64asm/src/opcode.enum,
and add a corresponding entry into the table in the right place.

**Comment by rknath** [comment]
Thanks a lot . Please let me know if something else ( other hard coded things ) comes up regarding this issue.

**Comment by eschkufz** [comment]
I believe there are a few things in the validator (berkeley would know for
sure) that rely on this as well.

At the very least, I think there are a few arrays that will give you
compile errors if you don't adjust the size appropriately.

**Comment by rknath** [comment]
yes .. I believe I fixed many of those.  

src/ext/x64asm/src/instruction.cc:32:array<const char*, 3804> att_ {{
src/ext/x64asm/src/instruction.cc:988:const array<size_t, 3804> Instruction::arity_ {{ 
src/ext/x64asm/src/instruction.cc:995:const array<array<Instruction::Properties, 4>, 3804> Instruction::properties_ {{
src/ext/x64asm/src/instruction.cc:1002:const array<array<Type, 4>, 3804> Instruction::type_ {{
src/ext/x64asm/src/instruction.cc:1009:const array<int, 3804> Instruction::mem_index_ {{
src/ext/x64asm/src/instruction.cc:1016:const array<RegSet, 3804> Instruction::implicit_must_read_set_ {{
src/ext/x64asm/src/instruction.cc:1023:const array<RegSet, 3804> Instruction::implicit_maybe_read_set_ {{
src/ext/x64asm/src/instruction.cc:1030:const array<RegSet, 3804> Instruction::implicit_must_write_set_ {{
src/ext/x64asm/src/instruction.cc:1037:const array<RegSet, 3804> Instruction::implicit_maybe_write_set_ {{
src/ext/x64asm/src/instruction.cc:1044:const array<RegSet, 3804> Instruction::implicit_must_undef_set_ {{
src/ext/x64asm/src/instruction.cc:1051:const array<RegSet, 3804> Instruction::implicit_maybe_undef_set_ {{
src/ext/x64asm/src/instruction.cc:1058:const array<FlagSet, 3804> Instruction::flags_ {{
src/ext/x64asm/src/instruction.h:665:    static const std::array<size_t, 3804> arity_;
src/ext/x64asm/src/instruction.h:666:    static const std::array<std::array<Properties, 4>, 3804> properties_;
src/ext/x64asm/src/instruction.h:667:    static const std::array<std::array<Type, 4>, 3804> type_;
src/ext/x64asm/src/instruction.h:668:		static const std::array<int, 3804> mem_index_;
src/ext/x64asm/src/instruction.h:669:    static const std::array<RegSet, 3804> implicit_must_read_set_;
src/ext/x64asm/src/instruction.h:670:    static const std::array<RegSet, 3804> implicit_maybe_read_set_;
src/ext/x64asm/src/instruction.h:671:    static const std::array<RegSet, 3804> implicit_must_write_set_;
src/ext/x64asm/src/instruction.h:672:    static const std::array<RegSet, 3804> implicit_maybe_write_set_;
src/ext/x64asm/src/instruction.h:673:    static const std::array<RegSet, 3804> implicit_must_undef_set_;
src/ext/x64asm/src/instruction.h:674:    static const std::array<RegSet, 3804> implicit_maybe_undef_set_;
src/ext/x64asm/src/instruction.h:675:    static const std::array<FlagSet, 3804> flags_;
src/ext/x64asm/src/opcode.cc:23:std::array<const char*, 3804> att_ {{
src/validator/handler.cc:46:const array<const char*, 3804> Handler::att_ = {{
src/validator/handler.h:86:  static const std::array<const char*, 3804> att_;
tools/io/opc_set.cc:33:array<const char*, 3804> att_ {{

**Comment by bchurchill** [comment]
There shouldn't be anything in the validator that needs to change other than updating that fixed constant.  When I fix this issue I'm going to create a 'define' in an x64asm header file so we don't have to keep this terrible number hardcoded.

**Comment by eschkufz** [comment]
Its still going to be an issue with the cost functions. The contents of the
table will always need to be updated.

**Comment by bchurchill** [comment]
That's true.

**Comment by bchurchill** [comment]
The fix for this is in the master branch of x64asm now, and soon I'll push out a new version of stoke into the stoke-release repository that correctly handles this change.

**Comment by bchurchill** [comment]
This is all done in both stoke and x64asm now.  Sorry for the delay -- hopefully we'll be faster in the future.
