### ISSUE TITLE
linker should return better error messages

### ISSUE THREAD

**Issue by bchurchill** [eschkufz/x64asm#145]
i.e. *which symbol* had the problem.

**Comment by bchurchill** [comment]
One thing that really bugs me about stoke and x64asm is how often the variables/information I want just aren't available.  I'd have to do some real fishing to get this and it just doesn't seem worth it at 1am.

**Comment by bchurchill** [comment]
(you don't have to do it :)  )

**Comment by eschkufz** [comment]
This is a one-liner for me. I'll do it.

Ah... the bane of good software engineering. The code works, but it NEVER
does what you want, because it does close to nothing at all.

On Mon, Feb 9, 2015 at 1:11 AM, Berkeley Churchill <notifications@github.com
